// <auto-generated />
namespace IBA_Project1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class IdMovedToInterface : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IdMovedToInterface));
        
        string IMigrationMetadata.Id
        {
            get { return "202009282115109_IdMovedToInterface"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
